### ISSUE TITLE
When i go to the chart editor, the game crashes

### ISSUE THREAD

**Issue by Scaringcar** [UmbratheUmbreon/PublicDenpaEngine#1]
When i go to the chart, the game crashes.

So....
1. Go to 'A random song, or at the menu,'
2. Press '7'
3. (if you're in the menu, go to chart editor)

**Expected behavior**
the chart editor will open.

**Screenshots**
![image](https://user-images.githubusercontent.com/97506382/200231642-b41278e9-b9d8-419e-bcdb-cb0aad9d6532.png)
![image](https://user-images.githubusercontent.com/97506382/200231683-f4445e87-bfc1-4eb5-af87-01b13f2ea72b.png)

**Desktop (please complete the following information):**
 - Windows
 - Google Chrome
 - Windows 10

**Smartphone (please complete the following information):**
 - Lenovo
 - Windows
 - Google Chrome
 - Windows 10

**Additional context**
i re-install the engine, and the problem continues.

**Comment by UmbratheUmbreon** [comment]
Aaaaand i know exactly whats wrong
Give me a bit ill whip up a hotfix tommorow

**Comment by UmbratheUmbreon** [comment]
Fixed in latest update.

**Comment by Scaringcar** [comment]
thanks
