### ISSUE TITLE
Menu crash-

### ISSUE THREAD

**Issue by PDL2CGamejolt** [UmbratheUmbreon/PublicDenpaEngine#10]
**Describe the bug**
When I go to the main menu in my source code edit, it crashes with a "Null Object Reference".
**To Reproduce**
1. Go to the Main Menu
2. See error
(Simple.)

**Expected behavior**
I expected me to go to the main menu.

**Screenshots**
![image](https://user-images.githubusercontent.com/94698464/212385331-916c623a-2b38-4481-87fa-7d69320e78cc.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 109 or 108 or somthing

**Additional context**

**Comment by UmbratheUmbreon** [comment]
Check line 153 in your source

**Comment by PDL2CGamejolt** [comment]
I removed the line of code. (if (!ClientPrefs.lowQuality) {
 			bgScroll.visible = true;
 			bgScroll2.visible = true;
 		})
I removed BGScroll.

**Comment by PDL2CGamejolt** [comment]
I removed any mention of BGScroll in the playstate because the Menu still crashed after I removed that line of code.

**Comment by PDL2CGamejolt** [comment]
But I think your thing should be compatible with actions.

**Comment by PDL2CGamejolt** [comment]
If the modder chooses to do actions
