### ISSUE TITLE
how i do make a wavy bg?

### ISSUE THREAD

**Issue by cubicalspike** [UmbratheUmbreon/PublicDenpaEngine#16]
i try with 

function onCreate()

    makeLuaSprite('bg1', 'backgrounds/cheater', -1400,-850);

    setLuaSpriteScrollFactor('bg1', 0.1, 0.1);

    addGlitchEffect('bg1', 1.5, 1.5);

    addLuaSprite('bg1', false)

scaleObject('bg1', 1.5, 1.5)

close(true); 

end

and it does not work

**Comment by UmbratheUmbreon** [comment]
![image](https://user-images.githubusercontent.com/101066547/226791002-ede30234-fbde-4af3-a0f7-e8b25b8b4111.png)

You need all four values for the function to work.
