### ISSUE TITLE
How do i make video cutscenes with lua😥😥😥

### ISSUE THREAD

**Issue by AqeelFromMyCloset** [UmbratheUmbreon/PublicDenpaEngine#19]
When I use a lua script for video cutscenes it cuts out
Please send an updated script of it in lua or hscript!
![image](https://user-images.githubusercontent.com/131583454/233829468-8bc97afc-83cc-4e12-80a9-d95d2afc9a38.png)
planitipgobia

**Comment by YanniZ06** [comment]
Not enough, information, make an issue that provides the information from the base template!!

**Comment by AqeelFromMyCloset** [comment]
when i used a lua script to use a cutscene it cuts most of the video and starts playing the song
