### ISSUE TITLE
A way to acess abstract classes in hscript

### ISSUE THREAD

**Issue by XTihX1** [UmbratheUmbreon/PublicDenpaEngine#20]
From what I've seen it's not currently possible to do that but if there's a way I'd like to know.

**Comment by YanniZ06** [comment]
Indeed, your best bet is to use the CoolUtil fromString functions for now, we‘ll find a way for proper support later!

**Comment by XTihX1** [comment]
The creators of the lore engine were able to do this using macros, I don't know how it works.

**Comment by YanniZ06** [comment]
If you set the abstracts manually then yes ofc it's possible,  very likely we'll do just that
