### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Jevilm** [UmbratheUmbreon/PublicDenpaEngine#21]
browser: opera gx
version: 22h2

![Screenshot (121)](https://user-images.githubusercontent.com/110422450/236630647-7369fd18-b2f5-4410-a9ab-97b3f88ca3c1.png)
i was charting a song and this happened. any help?

**Comment by UmbratheUmbreon** [comment]
This is a really annoying bug that we don't know how to fix, but we've been looking into it for a while now, and it will eventually be fixed.
