### ISSUE TITLE
[BUG REPORT] - Script not working

### ISSUE THREAD

**Issue by MINCREFAT** [UmbratheUmbreon/PublicDenpaEngine#23]
# Description:
My script is not working

## Reproduction:
Nothing to replicate the bug, its just my script wont work

## Expected Behavior
I want my script to work

**Comment by MemeHovy** [comment]
please give more details, just saying the script won't work is not enough details

**Comment by MINCREFAT** [comment]
idk what else to put lol

**Comment by MINCREFAT** [comment]
i was also thinking this should have a wiki lol

**Comment by MemeHovy** [comment]
> idk what else to put lol

put debug logs and other useful info so we can help figure out the issue

**Comment by MINCREFAT** [comment]
wdym by "debug logs"

**Comment by MINCREFAT** [comment]
ok idk what to do so im going to close this
