### ISSUE TITLE
This happened suddenly and i dont know why

### ISSUE THREAD

**Issue by NGIndustries** [UmbratheUmbreon/PublicDenpaEngine#25]
Paths.hx (line 380)
PlayState.hx (line 6201)
PlayState.hx (line 2537)
flixel/FlxGame.hx (line 637)
flixel/FlxGame.hx (line 724)
flixel/FlxGame.hx (line 677)
flixel/FlxGame.hx (line 545)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference
Please report this error to the GitHub page: https://github.com/UmbratheUmbreon/PublicDenpaEngine

> Crash Handler written by: sqirra-rng

i might be stupid or something, but i dont know what to do, i cant load up any songs at all, ive tried remaking the weeks, and it still dosnt work! what do i do?

**Comment by MemeHovy** [comment]
missing vocals file or incorrect vocals format

**Comment by NGIndustries** [comment]
the weird thing is, All song files are correct and none are missing, is there another cause for this issue?

**Comment by MemeHovy** [comment]
make sure your song files are in the correct file format, have you used an audio converter to convert them into ogg?

**Comment by NGIndustries** [comment]
nope

**Comment by NGIndustries** [comment]
I think I have a few ideas of what is causing the problem. I keep reskinning the menu icons, does that effect freeplay in any way? and if it does, why
