### ISSUE TITLE
[BUG REPORT] - I cant reskin the menu icons without it crashing when I enter fp

### ISSUE THREAD

**Issue by NGIndustries** [UmbratheUmbreon/PublicDenpaEngine#26]
# Description:
FreeplayState.hx (line 221)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference!
Please report this error to the GitHub page
(Will automatically open when exiting!)
Alternatively, report it in the official server
(Will also be opened automatically!)

Original CrashHandler code written by squirra-rng (https://github.com/gedehari)

I cannot reskin the menu icons without freeplay crashing when i enter into the menu

## Reproduction:

how to replicate it : reskin the freeplay menu icon and enter into the menu after restarting the game

## Expected Behavior

i excected the fp menu to just open as normal

ALSO, I do not use source so don't get on me for that

**Comment by YanniZ06** [comment]
could you link your reskinned assets and show the folder you put them in etc?? as much info as we can get

**Comment by UmbratheUmbreon** [comment]
Your week JSON is invalid, and does not have a proper bg color value for one or more of the songs.
