### ISSUE TITLE
How to Time Signature

### ISSUE THREAD

**Issue by naether** [UmbratheUmbreon/PublicDenpaEngine#27]
i opened an unfinished psych engine chart to continue charting it in denpa engine
the song is at a 5/4 time signature but denpa seems to interpret it as 4/4
In the section tab the step lengths are correct at 20 step lengths, however the step lengths option doesn't seem to do anything 

i don't know if it's already a feature and i just didn't find it or don't know how to use it so i apologize in advance

**Comment by UmbratheUmbreon** [comment]
@naether  time signatures are not supported in 0.8.1, however, they will be fully supported in update codename whale, which is the next major update. Time signatures will work exactly how you'd expect them to, unlike Psych
