### ISSUE TITLE
Game keeps on crashing!

### ISSUE THREAD

**Issue by AqeelFromMyCloset** [UmbratheUmbreon/PublicDenpaEngine#30]
The game crashes while testing a song, is there a way to fix this or is this a bug?

**Comment by MemeHovy** [comment]
can you provide more details?

**Comment by MemeHovy** [comment]
like debug logs and such?

**Comment by AqeelFromMyCloset** [comment]
when I was testing a song, it crashed at beat 80
the bpm is 174

**Comment by MemeHovy** [comment]
> when I was testing a song, it crashed at beat 80 the bpm is 174

any crash handler logs you can show?

**Comment by AqeelFromMyCloset** [comment]
i'll screenshot it if it happens again

**Comment by MemeHovy** [comment]
> i'll screenshot it if it happens again

okay 👍🏻

**Comment by AqeelFromMyCloset** [comment]
ok here it is 
![2023_06_30_0et_Kleki](https://github.com/UmbratheUmbreon/PublicDenpaEngine/assets/131583454/a7fba6b0-928e-4ece-97cd-027610f200fb)

**Comment by MemeHovy** [comment]
line 3353 refers to this `if (daNote.animation.curAnim.name.endsWith('tail'))` so it seems something might be wrong with the sustain animation with your notes texture

**Comment by AqeelFromMyCloset** [comment]
i don't understand cause i don't use source (because i love suffering) so can you explain it in a simpler form

**Comment by MemeHovy** [comment]
> i don't understand cause i don't use source (because i love suffering) so can you explain it in a simpler form

well, make sure your notes XML isn't screwed up

**Comment by MemeHovy** [comment]
have you modified it in any way?

**Comment by AqeelFromMyCloset** [comment]
no

**Comment by MemeHovy** [comment]
> no

alright, well I'll see what I can do later

**Comment by AqeelFromMyCloset** [comment]
alr

**Comment by AqeelFromMyCloset** [comment]
ok so it was just a broken note

**Comment by AqeelFromMyCloset** [comment]
so yeah note bug
