### ISSUE TITLE
[BUG REPORT] - The game crashes when it reaches the section where the 3rd strums were found in chart!

### ISSUE THREAD

**Issue by JergamerGamer11** [UmbratheUmbreon/PublicDenpaEngine#31]
# Description:
PlayState.hx (line 3320)
flixel/group/FlxGroup.hx (line 769)
PlayState.hx (line 3306)
flixel/FlxState.hx (line 213)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference!
Please report this error to the GitHub page
(Will automatically open when exiting!)
Alternatively, report it in the official server
(Will also be opened automatically!)

Original CrashHandler code written by squirra-rng (https://github.com/gedehari)

The game crashed about 4 times and still crashing when the 3rd strums were found in the charting.

## Reproduction:
tutorial to replicate it: idk

## Expected Behavior
I expected for it to work.

**Comment by MemeHovy** [comment]
line 3320 refers to this `daNote.distance = ((strumGroup.members[daNote.noteData].downScroll ? 0.45 : -0.45) * (Conductor.songPosition - daNote.strumTime) * songSpeed);`
also we need the tutorial to replicate the issue, otherwise we can't help you fix it

**Comment by MemeHovy** [comment]
altho, what you could do is `if (strumGroup.members[daNote.noteData] != null)` as a little solution to the issue

**Comment by JergamerGamer11** [comment]
ok. but it got fixed itself. sooo. what's the main point of this question.
