### ISSUE TITLE
[BUG REPORT] - Game crashes when chart is found.

### ISSUE THREAD

**Issue by JergamerGamer11** [UmbratheUmbreon/PublicDenpaEngine#32]
# Description:
PlayState.hx (line 6535)
PlayState.hx (line 5358)
PlayState.hx (line 3369)
flixel/group/FlxGroup.hx (line 769)
PlayState.hx (line 3306)
flixel/FlxState.hx (line 213)
flixel/FlxGame.hx (line 752)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl/events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)

Uncaught Error: Null Object Reference!
Please report this error to the GitHub page
(Will automatically open when exiting!)
Alternatively, report it in the official server
(Will also be opened automatically!)

Original CrashHandler code written by squirra-rng (https://github.com/gedehari)

The game crashed when the chart was found.

## Reproduction:
tutorial: at random times. the game would crash when the song loaded in. and stay like that until it was fixed

## Expected Behavior
I expected the chart would be fine. and not crash. and play normally

**Comment by MemeHovy** [comment]
![image](https://github.com/UmbratheUmbreon/PublicDenpaEngine/assets/124418090/ed97741f-01b6-41b8-98ab-7da7df0ead22)
hmmm

**Comment by MemeHovy** [comment]
it might be a issue with the song parsing the mustHitSection var

**Comment by JergamerGamer11** [comment]
ok.

**Comment by JergamerGamer11** [comment]
I hope this can be fixed without source.

**Comment by MemeHovy** [comment]
> I hope this can be fixed without source.

likely not

**Comment by JergamerGamer11** [comment]
ok.

**Comment by UmbratheUmbreon** [comment]
This issue is fixed in the Whale update which has a public demo version available in the discord server if you wish to use it.
You'd need to modify source to fix it though.
