### ISSUE TITLE
[BUG REPORT] - Error when compiling

### ISSUE THREAD

**Issue by jesseydeanimator** [UmbratheUmbreon/PublicDenpaEngine#36]
When i try to compile, i get this error message:
source/flixel/system/frontEnds/SoundFrontEnd.hx:9: characters 8-29 : Type not found : flixel.sound.FlxSound
source/flixel/system/frontEnds/SoundFrontEnd.hx:10: characters 8-34 : Type not found : flixel.sound.FlxSoundGroup
C:/HaxeToolkit/haxe/lib/flixel/5,2,2/flixel/system/FlxSoundGroup.hx:83: characters 10-25 : Cannot access private field updateTransform
export/release/windows/haxe/ApplicationMain.hx:151: characters 5-36 : ... Called from macro here
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
source/FunkinLua.hx:20: characters 8-29 : Type not found : flixel.sound.FlxSound
source/Alphabet.hx:6: characters 8-29 : Type not found : flixel.sound.FlxSound
source/Alphabet.hx:159: characters 20-28 : Type not found : FlxSound
source/DialogueBoxDenpa.hx:457: characters 11-23 : Alphabet has no field killTheTimer
source/DialogueBoxDenpa.hx:464: characters 12-28 : Class<Alphabet> has no field setDialogueSound
source/Alphabet.hx:70: characters 5-19 : Unknown identifier : startTypedText
source/Alphabet.hx:124: characters 5-22 : Unknown identifier : consecutiveSpaces
source/Alphabet.hx:134: characters 9-26 : Unknown identifier : consecutiveSpaces
source/Alphabet.hx:137: characters 5-22 : Unknown identifier : consecutiveSpaces
source/FreeplayState.hx:11: characters 8-29 : Type not found : flixel.sound.FlxSound
source/FreeplayState.hx:304: characters 28-36 : Type not found : FlxSound
source/PauseSubState.hx:9: characters 8-29 : Type not found : flixel.sound.FlxSound
source/PauseSubState.hx:33: characters 17-25 : Type not found : FlxSound
source/FunkinLua.hx:1747: characters 18-26 : Type not found : FlxSound
source/FunkinLua.hx:1785: characters 18-26 : Type not found : FlxSound
source/SoundTestState.hx:154: characters 17-38 : Class<FreeplayState> has no field destroyFreeplayVocals
source/MusicBeatState.hx:125: characters 17-38 : Class<FreeplayState> has no field destroyFreeplayVocals
source/ManualSubState.hx:6: characters 8-29 : Type not found : flixel.sound.FlxSound
source/ManualSubState.hx:16: characters 17-25 : Type not found : FlxSound
source/Alphabet.hx:25: characters 3-10 : Unknown identifier : scaledY
source/editors/DialogueEditorState.hx:254: characters 12-28 : Class<Alphabet> has no field setDialogueSound
source/editors/DialogueCharacterEditorState.hx:74: characters 12-28 : Class<Alphabet> has no field setDialogueSound
source/PatchState.hx:292: characters 43-50 : Alphabet has no field scaledY
source/PatchState.hx:298: characters 23-30 : Alphabet has no field scaledY
source/PatchState.hx:308: characters 43-50 : Alphabet has no field scaledY
source/PatchState.hx:310: characters 23-30 : Alphabet has no field scaledY
source/options/BaseOptionsMenu.hx:123: characters 51-82 : String should be Float
source/options/BaseOptionsMenu.hx:123: characters 51-82 : ... For function argument 'x'
source/Alphabet.hx:91: characters 3-20 : Unknown identifier : consecutiveSpaces
source/Alphabet.hx:106: characters 5-19 : Unknown identifier : startTypedText
source/options/OptionsSubState.hx:1247: characters 87-89 : Int should be String
source/options/OptionsSubState.hx:1247: characters 87-89 : ... For optional function argument 'text'
source/options/OptionsSubState.hx:1289: characters 87-89 : Int should be String
source/options/OptionsSubState.hx:1289: characters 87-89 : ... For optional function argument 'text'
source/options/OptionsSubState.hx:1297: characters 87-89 : Int should be String
source/options/OptionsSubState.hx:1297: characters 87-89 : ... For optional function argument 'text'
source/options/OptionsSubState.hx:2049: characters 32-37 : String should be Float
source/options/OptionsSubState.hx:2049: characters 32-37 : ... For function argument 'x'
source/options/OptionsSubState.hx:2057: characters 32-37 : String should be Float
source/options/OptionsSubState.hx:2057: characters 32-37 : ... For function argument 'x'
source/options/OptionsSubState.hx:1996: characters 27-37 : AttachedText has no field sprTracker
source/options/OptionsSubState.hx:2003: characters 24-34 : AttachedText has no field sprTracker
source/options/BaseOptionsMenu.hx:167: characters 43-50 : Alphabet has no field scaledY
source/options/BaseOptionsMenu.hx:174: characters 23-30 : Alphabet has no field scaledY
source/options/OptionsSubState.hx:1332: characters 13-20 : AttachedText has no field offsetX (Suggestion: offset)
source/options/OptionsSubState.hx:1332: characters 45-52 : AttachedText has no field offsetX (Suggestion: offset)
source/options/OptionsSubState.hx:1332: characters 84-94 : AttachedText has no field sprTracker
source/options/OptionsSubState.hx:2018: characters 20-30 : AttachedText has no field sprTracker
source/options/OptionsSubState.hx:2027: characters 23-33 : AttachedText has no field sprTracker
source/options/OptionsSubState.hx:2105: characters 27-37 : AttachedText has no field sprTracker
source/options/OptionsSubState.hx:2111: characters 24-34 : AttachedText has no field sprTracker
source/options/OptionsState.hx:56: characters 17-38 : Class<FreeplayState> has no field destroyFreeplayVocals
source/CreditsState.hx:317: characters 43-50 : Alphabet has no field scaledY
source/CreditsState.hx:323: characters 23-30 : Alphabet has no field scaledY
source/CreditsState.hx:333: characters 43-50 : Alphabet has no field scaledY
source/CreditsState.hx:335: characters 23-30 : Alphabet has no field scaledY
source/GameplayChangersSubstate.hx:170: characters 51-82 : String should be Float
source/GameplayChangersSubstate.hx:170: characters 51-82 : ... For function argument 'x'
source/StoryMenuState.hx:363: characters 19-40 : Class<FreeplayState> has no field destroyFreeplayVocals
source/PlayState.hx:489: characters 17-38 : Class<FreeplayState> has no field destroyFreeplayVocals
source/PlayState.hx:493: characters 17-25 : Class<PauseSubState> has no field songName
source/PlayState.hx:1728: characters 21-29 : Class<PauseSubState> has no field songName
source/PlayState.hx:1729: characters 35-43 : Class<PauseSubState> has no field songName
source/PlayState.hx:3184: characters 36-67 : Too many arguments
source/PlayState.hx:3184: characters 36-67 : ... For function argument 'SubState'

Please help me fix this, i have tried everything.

**Comment by MemeHovy** [comment]
denpa engine is currently not compatible with flixel 5.3 and flixel addons 3

**Comment by jesseydeanimator** [comment]
> nted

So what version should I use?

**Comment by jesseydeanimator** [comment]
> flixel 5.2.2 and flixel addons 3.0.2

I did that and now i get this:source/flixel/system/frontEnds/SoundFrontEnd.hx:9: characters 8-29 : Type not found : flixel.sound.FlxSound
source/flixel/system/frontEnds/SoundFrontEnd.hx:10: characters 8-34 : Type not found : flixel.sound.FlxSoundGroup
C:/HaxeToolkit/haxe/lib/flixel/5,2,2/flixel/system/FlxSoundGroup.hx:83: characters 10-25 : Cannot access private field updateTransform
source/FunkinLua.hx:20: characters 8-29 : Type not found : flixel.sound.FlxSound
source/Alphabet.hx:6: characters 8-29 : Type not found : flixel.sound.FlxSound
source/Alphabet.hx:159: characters 20-28 : Type not found : FlxSound
source/animateatlas/AtlasFrameMaker.hx:26: lines 26-127 : ... Defined in this class
source/DialogueBoxDenpa.hx:457: characters 11-23 : Alphabet has no field killTheTimer
source/DialogueBoxDenpa.hx:464: characters 12-28 : Class<Alphabet> has no field setDialogueSound
source/Alphabet.hx:70: characters 5-19 : Unknown identifier : startTypedText
source/Alphabet.hx:124: characters 5-22 : Unknown identifier : consecutiveSpaces
source/Alphabet.hx:134: characters 9-26 : Unknown identifier : consecutiveSpaces
source/Alphabet.hx:137: characters 5-22 : Unknown identifier : consecutiveSpaces
source/FreeplayState.hx:11: characters 8-29 : Type not found : flixel.sound.FlxSound
source/FreeplayState.hx:304: characters 28-36 : Type not found : FlxSound
source/PlayState.hx:57: lines 57-7061 : ... Defined in this class
source/PauseSubState.hx:9: characters 8-29 : Type not found : flixel.sound.FlxSound
source/PauseSubState.hx:33: characters 17-25 : Type not found : FlxSound
source/FunkinLua.hx:40: lines 40-2490 : ... Defined in this class
source/FunkinLua.hx:1747: characters 18-26 : Type not found : FlxSound
source/FunkinLua.hx:1785: characters 18-26 : Type not found : FlxSound
source/SoundTestState.hx:154: characters 17-38 : Class<FreeplayState> has no field destroyFreeplayVocals
source/MusicBeatState.hx:125: characters 17-38 : Class<FreeplayState> has no field destroyFreeplayVocals
source/ManualSubState.hx:6: characters 8-29 : Type not found : flixel.sound.FlxSound
source/ManualSubState.hx:16: characters 17-25 : Type not found : FlxSound
source/MusicBeatState.hx:16: lines 16-225 : ... Defined in this class
source/Alphabet.hx:25: characters 3-10 : Unknown identifier : scaledY
source/editors/DialogueEditorState.hx:254: characters 12-28 : Class<Alphabet> has no field setDialogueSound
source/editors/DialogueCharacterEditorState.hx:74: characters 12-28 : Class<Alphabet> has no field setDialogueSound
source/PatchState.hx:292: characters 43-50 : Alphabet has no field scaledY
source/PatchState.hx:298: characters 23-30 : Alphabet has no field scaledY
source/PatchState.hx:308: characters 43-50 : Alphabet has no field scaledY
source/PatchState.hx:310: characters 23-30 : Alphabet has no field scaledY
source/options/BaseOptionsMenu.hx:123: characters 51-82 : String should be Float
source/options/BaseOptionsMenu.hx:123: characters 51-82 : ... For function argument 'x'
source/Alphabet.hx:91: characters 3-20 : Unknown identifier : consecutiveSpaces
source/Alphabet.hx:106: characters 5-19 : Unknown identifier : startTypedText
source/options/OptionsSubState.hx:1247: characters 87-89 : Int should be String
source/options/OptionsSubState.hx:1247: characters 87-89 : ... For optional function argument 'text'
source/options/OptionsSubState.hx:1289: characters 87-89 : Int should be String
source/options/OptionsSubState.hx:1289: characters 87-89 : ... For optional function argument 'text'
source/options/OptionsSubState.hx:1297: characters 87-89 : Int should be String
source/options/OptionsSubState.hx:1297: characters 87-89 : ... For optional function argument 'text'
source/options/OptionsSubState.hx:2049: characters 32-37 : String should be Float
source/options/OptionsSubState.hx:2049: characters 32-37 : ... For function argument 'x'
source/options/OptionsSubState.hx:2057: characters 32-37 : String should be Float
source/options/OptionsSubState.hx:2057: characters 32-37 : ... For function argument 'x'
source/options/OptionsSubState.hx:1996: characters 27-37 : AttachedText has no field sprTracker
source/options/OptionsSubState.hx:2003: characters 24-34 : AttachedText has no field sprTracker
source/options/BaseOptionsMenu.hx:167: characters 43-50 : Alphabet has no field scaledY
source/options/BaseOptionsMenu.hx:174: characters 23-30 : Alphabet has no field scaledY
source/options/OptionsSubState.hx:1332: characters 13-20 : AttachedText has no field offsetX (Suggestion: offset)
source/options/OptionsSubState.hx:1332: characters 45-52 : AttachedText has no field offsetX (Suggestion: offset)
source/options/OptionsSubState.hx:1332: characters 84-94 : AttachedText has no field sprTracker
source/options/OptionsSubState.hx:2018: characters 20-30 : AttachedText has no field sprTracker
source/options/OptionsSubState.hx:2027: characters 23-33 : AttachedText has no field sprTracker
source/options/OptionsSubState.hx:2105: characters 27-37 : AttachedText has no field sprTracker
source/options/OptionsSubState.hx:2111: characters 24-34 : AttachedText has no field sprTracker
source/options/OptionsState.hx:56: characters 17-38 : Class<FreeplayState> has no field destroyFreeplayVocals
source/CreditsState.hx:317: characters 43-50 : Alphabet has no field scaledY
source/CreditsState.hx:323: characters 23-30 : Alphabet has no field scaledY
source/CreditsState.hx:333: characters 43-50 : Alphabet has no field scaledY
source/CreditsState.hx:335: characters 23-30 : Alphabet has no field scaledY
source/GameplayChangersSubstate.hx:170: characters 51-82 : String should be Float
source/GameplayChangersSubstate.hx:170: characters 51-82 : ... For function argument 'x'
source/StoryMenuState.hx:363: characters 19-40 : Class<FreeplayState> has no field destroyFreeplayVocals
source/PlayState.hx:489: characters 17-38 : Class<FreeplayState> has no field destroyFreeplayVocals
source/PlayState.hx:493: characters 17-25 : Class<PauseSubState> has no field songName
source/PlayState.hx:1728: characters 21-29 : Class<PauseSubState> has no field songName
source/PlayState.hx:1729: characters 35-43 : Class<PauseSubState> has no field songName
source/PlayState.hx:3184: characters 36-67 : Too many arguments
source/PlayState.hx:3184: characters 36-67 : ... For function argument 'SubState'

Pleasr help meee

**Comment by jesseydeanimator** [comment]
Nvm i figured it out, THANK UU

**Comment by MemeHovy** [comment]
np, now close the issue

**Comment by UmbratheUmbreon** [comment]
Please actually follow the compilation instructions and use the correct library and haxe versions.
