### ISSUE TITLE
Game keeps crashing every time I add an event.

### ISSUE THREAD

**Issue by coolthingsLmfao** [UmbratheUmbreon/PublicDenpaEngine#40]
So, I'm just trying to chart a song, everything works, no corrupted chart data or unsupported data. So i try to add a subtitle (or any event) and it crashes and comes up with the crash handler.

**Comment by MemeHovy** [comment]
show the error

**Comment by UmbratheUmbreon** [comment]
You need an error log or this cannot be resolved.
