### ISSUE TITLE
[BUG REPORT] - Game Crashes everytime i port in a character

### ISSUE THREAD

**Issue by VaporWave3** [UmbratheUmbreon/PublicDenpaEngine#43]

**Comment by MemeHovy** [comment]
can you give us more details? like crash logs or anything?

**Comment by VaporWave3** [comment]
> can you give us more details? like crash logs or anything?

sure

Character.hx (line 496)
Character.hx (line 211)
Playstate.hx (line 642)
flixel/FlxGame.hx (line 642)
flixel/FlxGame.hx (line 729)
flixel/FlxGame.hx (line 682)
flixel/FlxGame.hx (line 556)
openfl(events/EventDispatcher.hx (line 402)
openfl/display/DisplayObject.hx (line 1399)


Your Character .json may be invalid!



Even tho i chose dad, this happens

**Comment by MemeHovy** [comment]
you need to make sure you didn’t tamper with the character’s json with notepad or anything, like the error says

**Comment by UmbratheUmbreon** [comment]
Your JSON does not have an "image" field, so the game crashes trying to read it.
