### ISSUE TITLE
when i press the appclaition and i showing me an error ,do you know how to fix it?

### ISSUE THREAD

**Issue by joolboy** [UmbratheUmbreon/PublicDenpaEngine#44]
# Description:
when  open the engine it keeping saying error:process cration failure : wmic , it keep saying that

E.G: "When scrolling the mouse the Sprite disappears for a split second and after a tiny bit reappears. This is not easy to notice, but can ruin the immersion."

## Reproduction:
Give clear instructions on how to replicate the bug (if possible), otherwise provide as much info as possible on where the bug happened and what might have caused it (should be given nonetheless).
This info includes, but is not limited to:
- State the Bug occured in
- Object that caused the Bug (if its related to a specific game-object that is)
- Build type the bug appeared in (Debug? Release?)
- Possible Alternative Options it could be related to

EG: "Scroll up the Mouse wheel on FreeplayState, the top-most Icon will disappear for a second when it is almost offscreen. This bug only happens when the lowQuality mode is enabled. Cause could be accidental unloading of the Icon before its intended to."

## Expected Behavior

EG: "When scrolling the sprite should not disappear until it is offscreen."

**Comment by UmbratheUmbreon** [comment]
Please follow the issue template so we can fully understand what has occurred to cause this crash. Crash Logs are necessary.
