### ISSUE TITLE
How to add dialogue?

### ISSUE THREAD

**Issue by Porcupine2009** [UmbratheUmbreon/PublicDenpaEngine#49]
I tried adding it in assets/data/dialogue/tutorial and mods/data/dialogue/tutorial and nothing worked. I also tried putting it in assets/data/charts/tutorial like Psych Engine but that failed as well.

Am i doing something wrong?

Unless it is a bug, this is NOT a bug report.

**Comment by UmbratheUmbreon** [comment]
Please use the issues tab for bug reports and not for questions.

**Comment by Porcupine2009** [comment]
Whoops sorry @UmbratheUmbreon! Didn't see the "discussion" tab lol
