### ISSUE TITLE
As soon as the health thing gets to 100%, it doesn't rise when after it goes down to below 99%, it just keeps on going lower.

### ISSUE THREAD

**Issue by githubisveryepic** [UmbratheUmbreon/PublicDenpaEngine#5]
**Describe the bug**
The title kind of says it all, I guess. But it doesn't rise to anything higher after it goes down to below 99% no matter how many notes I press. is this just an issue with porting characters from old versions like Denpa Engine V0.5.1 to Denpa Engine V0.7.0b, or is it something else?

**To Reproduce**
I mean, I don't really know. I charted a song, put a character from V0.5.1 in to V0.7.0b just so the character is there in the song (this character is the opponent), put the character in the song, and once the health for Boyfriend reaches 100% then down to something like below 99%, it doesn't rise (it's not supposed to rise if it's 100%, but even when it goes down after 100%, it doesn't rise again), so basically, I just have to not miss at all. There are no lua scripts, or events in the song currently, so I do not know this is is happening.

**Expected behavior**
I expected it to work normally.

**Comment by MemeHoovy** [comment]
...are you saying that the healthbar doesn't go up as soon as you reach 100% health, and when the healthbar goes below 99%, it doesn't go up?

**Comment by githubisveryepic** [comment]
so basically
it reaches 100%, everything seems to be perfectly fine
but then a huge thing of notes comes out of no where and boom it's 39% health
but then, no matter how many notes i press next, it doesn't bring the health up
meaning, after i reach 100% health, i have to not miss at all
sorry if this is hard to understand, i'm bad at explaining.

**Comment by MemeHoovy** [comment]
okay, well if I'm reading this correctly, if they're a bunch of spammy notes like seen here
https://www.youtube.com/watch?v=5d9GOpuT6kM
then I'm pretty sure we can't fix it, and that it's fucked, but otherwise, we'll look into it in the dev branch

**Comment by MemeHoovy** [comment]
honestly @UmbratheUmbreon you should invite me to the repo to help manage things here

**Comment by githubisveryepic** [comment]
it's not something like "IP", and i am also pressing the notes correctly i think

**Comment by MemeHoovy** [comment]
skill issue is something we can't fix -_-

**Comment by githubisveryepic** [comment]
it's not skill issue the health just keeps going down + i'm actually pressing the notes correctly
usually, it would be fast with going between up and down but here it's just going down
i've charted extremely hard things in denpa engine v0.5.1 (harder than the song i've charted in the current denpa engine build, which also means a bit hard) but i've never seen this problem in denpa engine v0.5.1

**Comment by githubisveryepic** [comment]
i'm gonna try making a new json for the character

**Comment by MemeHoovy** [comment]
well, that might be because a character has health drain tied to them

**Comment by githubisveryepic** [comment]
health drain doesn't usually stop health growth i think

**Comment by githubisveryepic** [comment]
also i checked the character in-game, doesn't seem to have health drain

**Comment by MemeHoovy** [comment]
well uh, idk, I'll look through it on the dev branch

**Comment by MemeHoovy** [comment]
hey @githubisveryepic I think this might be due to smooth health, there was a change in 0.7.0 that added this that might be the culprit here, I'mma try to fix it but don't count on it

**Comment by githubisveryepic** [comment]
alright

**Comment by MemeHoovy** [comment]
okay, you're just gonna have to wait until the next update, idk if I entirely fixed it but yeah

**Comment by MemeHoovy** [comment]
@githubisveryepic new info, according to AT, you might've had danger misses on

**Comment by githubisveryepic** [comment]
oops i had danger misses on
