### ISSUE TITLE
[BUG REPORT] - Null object reference

### ISSUE THREAD

**Issue by THOMAWESOMENESSyt** [UmbratheUmbreon/PublicDenpaEngine#52]
When i try to boot up the engine all it says is "Null object reference" and then it crashes... how do i fix this? i did a reset to my psych and stuff but it still wont work!

**Comment by moxie-coder** [comment]
are there any error logs or anything that have shown up? what version are you using?

**Comment by THOMAWESOMENESSyt** [comment]
to answer your first question, i do not know how to see error logs... and for the second question... i am using the GB version and

**Comment by UmbratheUmbreon** [comment]
Please provide error logs, otherwise this issue cannot be addressed.

**Comment by THOMAWESOMENESSyt** [comment]
how do i even LOOK at error logs?

**Comment by THOMAWESOMENESSyt** [comment]
![image](https://github.com/UmbratheUmbreon/PublicDenpaEngine/assets/94532444/2da258ae-65f4-4e93-95a5-1fc8157f0787)
all it says is "null object reference" it doesnt even have any details at all

**Comment by THOMAWESOMENESSyt** [comment]
and the crash handler doesn't say anything either!

**Comment by 2Schoolhouse** [comment]
I haven't used Denpa Engine in a while, so correct me if I'm wrong, but Denpa might generate error logs somewhere in your files.
