### ISSUE TITLE
Why can't I add mods in the game?

### ISSUE THREAD

**Issue by Alfredo12334** [UmbratheUmbreon/PublicDenpaEngine#56]
when I put a mod into the mods folder it doesn't work, I mean it loads the game but the mod doesn't work , I would like that they add a mods section to load the mods

**Comment by Alfredo12334** [comment]
that didn't work, but I moved some mod files and it did work

**Comment by PetscopF** [comment]
Oh, damn, I didn't realize that this was Denpa Engine - I haven't used it in a while, but still have it in my Watch list. It kind of disrupted me there for a second.
