### ISSUE TITLE
How i add music player

### ISSUE THREAD

**Issue by eargau** [UmbratheUmbreon/PublicDenpaEngine#7]
I don't really how add music player in mods.

and i will wait reply

**Comment by MemeHoovy** [comment]
use code from here https://github.com/MoldyGH/VsDave

**Comment by eargau** [comment]
i mean test sounds. :/

**Comment by UmbratheUmbreon** [comment]
@eargau as of right now, source code required. 0.8.0 however will allow you to add custom ones easily.

**Comment by eargau** [comment]
Oh ok.

**Comment by eargau** [comment]
btw when 0.8.0?
